### ISSUE TITLE
slideCapt 滑动组件最外层的div宽度，写死了，不灵活，也不支持style, classname 重写。

### ISSUE THREAD

**Issue by darkmice** [wenlng/go-captcha-react#1]

**Comment by wenlng** [comment]
你好，可以使用 config 配置
参考文档：http://gocaptcha.wencodes.com/package/react/#%E6%BB%91%E5%8A%A8%E5%BC%8F

**Comment by darkmice** [comment]
> 你好，可以使用 config 配置 参考文档：http://gocaptcha.wencodes.com/package/react/#%E6%BB%91%E5%8A%A8%E5%BC%8F

这个config只能配置图片的宽度，我说的是最外层的div宽度， 我发现源码中不支持外部定义

**Comment by wenlng** [comment]
> > 你好，可以使用 config 配置 参考文档：http://gocaptcha.wencodes.com/package/react/#%E6%BB%91%E5%8A%A8%E5%BC%8F
> 
> 这个config只能配置图片的宽度，我说的是最外层的div宽度， 我发现源码中不支持外部定义

整个验证码宽度 = config.horizontalPadding + config.width，当然你也可以在外层套个div控制宽度并设置水平居中
