### ISSUE TITLE
拖动滑块时鼠标脱离滑块就触发了验证事件

### ISSUE THREAD

**Issue by 2233ggbb** [wenlng/go-captcha-react#3]
如标题，有时候我并不希望离开滑块就触发验证事件，这样操作起来比较困难，这个事件可以加一个参数来支持可选
<img width="721" alt="image" src="https://github.com/user-attachments/assets/af0d38fb-8647-4067-8ec2-367509c31199">

**Comment by wenlng** [comment]
嘿嘿，离开滑块后只会携带当前位置信息回调到 confirm 事件，这时你别在 confirm 中处理请求校验逻辑，只将当前的位置信息使用 useState 保存起来，等在其他地方触发验证时，再携带位置信息做请求API做验证就好了

**Comment by 2233ggbb** [comment]
> 嘿嘿，离开滑块后只会携带当前位置信息回调到 confirm 事件，这时你别在 confirm 中处理请求API校验逻辑，只将当前的位置信息使用 useState 保存起来，等在其他地方触发验证时，再携带位置信息做请求API做验证就好了

问题是离开滑块后无法继续拖动了，而且就你说的，我怎么判断他是否是因为离开滑块后触发的confirm事件还是因为别的触发的，如果额外加个按钮来触发验证，交互就更奇怪了

**Comment by wenlng** [comment]
> > 嘿嘿，离开滑块后只会携带当前位置信息回调到 confirm 事件，这时你别在 confirm 中处理请求API校验逻辑，只将当前的位置信息使用 useState 保存起来，等在其他地方触发验证时，再携带位置信息做请求API做验证就好了
> 
> 问题是离开滑块后无法继续拖动了，而且就你说的，我怎么判断他是否是因为离开滑块后触发的confirm事件还是因为别的触发的，如果额外加个按钮来触发验证，交互就更奇怪了

 v1.0.1 版本换了一种方式处理，更新版本号就好

**Comment by 2233ggbb** [comment]
> > > 嘿嘿，离开滑块后只会携带当前位置信息回调到 confirm 事件，这时你别在 confirm 中处理请求API校验逻辑，只将当前的位置信息使用 useState 保存起来，等在其他地方触发验证时，再携带位置信息做请求API做验证就好了
> > 
> > 
> > 问题是离开滑块后无法继续拖动了，而且就你说的，我怎么判断他是否是因为离开滑块后触发的confirm事件还是因为别的触发的，如果额外加个按钮来触发验证，交互就更奇怪了
> 
> v1.0.1 版本换了一种方式处理，更新版本就好

直接注释吗，简单粗暴 O_O

**Comment by wenlng** [comment]
> > > > 嘿嘿，离开滑块后只会携带当前位置信息回调到 confirm 事件，这时你别在 confirm 中处理请求API校验逻辑，只将当前的位置信息使用 useState 保存起来，等在其他地方触发验证时，再携带位置信息做请求API做验证就好了
> > > 
> > > 
> > > 问题是离开滑块后无法继续拖动了，而且就你说的，我怎么判断他是否是因为离开滑块后触发的confirm事件还是因为别的触发的，如果额外加个按钮来触发验证，交互就更奇怪了
> > 
> > 
> > v1.0.1 版本换了一种方式处理，更新版本就好
> 
> 直接注释吗，简单粗暴 O_O

不是直接注释，因为是要防止在按着滑块拖出了视窗口时松开鼠标会造成事件断流的场景，现在换成了结合监听 body 事件来辅助处理会更友好一些吧

**Comment by 2233ggbb** [comment]
> > > > > 嘿嘿，离开滑块后只会携带当前位置信息回调到 confirm 事件，这时你别在 confirm 中处理请求API校验逻辑，只将当前的位置信息使用 useState 保存起来，等在其他地方触发验证时，再携带位置信息做请求API做验证就好了
> > > > 
> > > > 
> > > > 问题是离开滑块后无法继续拖动了，而且就你说的，我怎么判断他是否是因为离开滑块后触发的confirm事件还是因为别的触发的，如果额外加个按钮来触发验证，交互就更奇怪了
> > > 
> > > 
> > > v1.0.1 版本换了一种方式处理，更新版本就好
> > 
> > 
> > 直接注释吗，简单粗暴 O_O
> 
> 不是直接注释，因为是要防止在按着滑块拖出了视窗口时松开鼠标会造成事件断流的场景，现在换成了结合监听 body 事件来辅助处理会更友好一些了

哦，好的，前面没细看，后面我再看一下

**Comment by 2233ggbb** [comment]
move 事件能否也改成监听body，现在按着滑块鼠标离开滑块后，事件不会断流，但是滑块也不会跟着移动，因为move事件挂在滑块上

**Comment by 2233ggbb** [comment]
> move 事件能否也改成监听body，现在按着滑块鼠标离开滑块后，事件不会断流，但是滑块也不会跟着移动，因为move事件挂在滑块上

move 事件能否也改成监听body，现在按着滑块鼠标离开滑块后，事件不会断流，但是滑块也不会跟着移动，因为move事件挂在滑块上

**Comment by 2233ggbb** [comment]
> > > > > 嘿嘿，离开滑块后只会携带当前位置信息回调到 confirm 事件，这时你别在 confirm 中处理请求API校验逻辑，只将当前的位置信息使用 useState 保存起来，等在其他地方触发验证时，再携带位置信息做请求API做验证就好了
> > > > 
> > > > 
> > > > 问题是离开滑块后无法继续拖动了，而且就你说的，我怎么判断他是否是因为离开滑块后触发的confirm事件还是因为别的触发的，如果额外加个按钮来触发验证，交互就更奇怪了
> > > 
> > > 
> > > v1.0.1 版本换了一种方式处理，更新版本就好
> > 
> > 
> > 直接注释吗，简单粗暴 O_O
> 
> 不是直接注释，因为是要防止在按着滑块拖出了视窗口时松开鼠标会造成事件断流的场景，现在换成了结合监听 body 事件来辅助处理

move 事件能否也改成监听body，现在按着滑块鼠标离开滑块后，事件不会断流，但是滑块也不会跟着移动，因为move事件挂在滑块上

**Comment by wenlng** [comment]
> move 事件能否也改成监听body，现在按着滑块鼠标离开滑块后，事件不会断流，但是滑块也不会跟着移动，因为move事件挂在滑块上

这个只允许在可滑动区内滑动，后面还要规划做行为轨迹校验的，你有特殊的情况建议fork一个版本出来根据需要去定制了

**Comment by wenlng** [comment]
在 v1.0.2 版本的 config 参数传递 scope: true 可以满足这种场景
https://github.com/wenlng/go-captcha-react/tree/v1.0.2
